routes/web.php
<?php

use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AdminPostController;

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Http\Controllers\PostController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\LikeController;
use App\Http\Controllers\PaymentController;

Route::get('/', [PostController::class, 'index'])->name('post.index');
Route::get('/post/{post}', [PostController::class, 'show'])->name('post.show');

Route::get('/post/search', [PostController::class, 'search'])->name('post.search');

Auth::routes(['verify' => true]);

Route::middleware('guest')->group(function () {
    Route::get('/register', [AuthController::class, 'indexRegister'])->name('indexRegister');
    Route::post('/register', [AuthController::class, 'register'])->name('register');
    Route::get('/login', [AuthController::class, 'index'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->name('customLogin');

});

Route::post('/logout', function () {
    Auth::logout();
    return redirect('/')->with('logoutMsg', 'Logout Successfully');
})->name('logout');

Route::get('/home', function () {
    return redirect('/');
});


Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/user/create', [PostController::class, 'showCreateForm'])->name('post.create')->middleware('subscription');
    Route::post('/user/create', [PostController::class, 'store'])->name('post.store')->middleware('subscription');
    Route::get('/user/posts/', [PostController::class, 'singleUserPosts'])->name('user.posts');
    Route::get('/user/posts/{id}', [PostController::class, 'edit'])->name('user.posts.edit');
    Route::put('/user/posts/{id}', [PostController::class, 'update'])->name('user.posts.update');
    Route::delete('/user/posts/{id}', [PostController::class, 'destroy'])->name('user.posts.delete');

    Route::get('posttable', [PostController::class, 'tableView'])->name('post.table');
    Route::get('posttable/sort-ascend', [PostController::class, 'sortByAscendTable'])->name('post.sort.ascend');
    Route::get('posttable/sort-older', [PostController::class, 'sortByOlderTable'])->name('post.sort.older');

    Route::get('/subscription/', [PaymentController::class, 'index'])->name('payment.index');
    Route::get('/subscription/silver', [PaymentController::class, 'silverSubscription'])->name('payment.silver');
    Route::get('/subscription/diamond', [PaymentController::class, 'diamondSubscription'])->name('payment.diamond');
    Route::get('/paypal-checkout/{price}', [PaymentController::class, 'paypalCheckout'])->name('paypal.checkout');

    Route::post('posts/{post}/like', [LikeController::class, 'store'])->name('posts.likes');
    Route::delete('posts/{post}/like', [LikeController::class, 'destroy'])->name('posts.likes');

    Route::post('comment/store/{post}',[CommentController::class,'store'])->name('comment.store');

});

Route::prefix('admin', 'verified')->name('admin.')->middleware('can:manage-users')->group(function () {
    Route::resource('/users', UserController::class)->except(['show', 'create', 'store']);
    Route::get('/posts/', [AdminPostController::class, 'index'])->name('posts.table');
    Route::delete('/posts/{id}', [AdminPostController::class, 'destroy'])->name('posts.delete');
    Route::get('/posts/{id}', [AdminPostController::class, 'edit'])->name('posts.edit');
    Route::put('/posts/{id}', [AdminPostController::class, 'update'])->name('posts.update');

    Route::get('posttable/sort-ascend', [AdminPostController::class, 'sortByAscendTable'])->name('post.sort.ascend');
    Route::get('posttable/sort-older', [AdminPostController::class, 'sortByOlderTable'])->name('post.sort.older');
    Route::get('posttable/sort-active', [AdminPostController::class, 'showActivePost'])->name('post.sort.active');
    Route::get('posttable/sort-notactive', [AdminPostController::class, 'showNotActivePost'])->name('post.sort.notactive');


    Route::post('/import', [UserController::class, 'import'])->name("user.import");
    Route::get('/export', [UserController::class, 'export'])->name("user.export");
});

resources/views/admin/edit_user.blade.php
@extends('layouts.app')

@section('content')
    <header>
        <div class="h-60 bg-gray-100 flex justify-center ">
            <div class="py-6 px-8   mt-20 bg-white rounded shadow-xl ">

                @if (session('status'))
                    <div class="bg-red-500 p-4 rounded-lg mb-6 text-white text-center">
                        {{ session('status') }}
                    </div>
                @endif

                <h1 class="font-bold text-base mb-2">Edit Roles: </h1>
                <form action="{{ route('admin.users.update', $user) }}" method="post">
                    @method('put')
                    @csrf
                    @foreach ($roles as $role)
                        <div class="form-check">
                            <input type="checkbox" name="roles[]" value="{{ $role->id }}">
                            <label for="">{{ $role->name }}</label>
                        </div>
                    @endforeach
                    <button type="submit"
                        class="bg-indigo-500 text-white font-bold w-full text-center rounded">Register</button>
                </form>
            </div>
        </div>
    </header>
@endsection

resources/views/admin/user_table.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <h1 class="float-left mt-4 text-xl">User Table</h1>

        <a href="{{ route('admin.user.export') }}" class="float-right mt-4 mr-10 mb-2 btn btn-primary">Export</a>
        <form action="{{ route('admin.user.import') }}" class="float-right" method="POST" enctype="multipart/form-data">
            @csrf
            <input type="file" name="file" class="btn mt-4 p-0 ">
            @error('file')
                <p class="float-left font-red">{{ $message }}</p>
            @enderror
            <input type="submit" value="import" class="float-right mt-4 mr-3 btn btn-success ">
        </form>
        @if ($users->count())

            @if (Session::has('success'))
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>Succeed</strong> {{ Session::get('success') }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif
            @if (Session::has('acsend'))
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>Succeed</strong> {{ session('acsend') }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif

            <table class="text-center w-full h-auto">
                <thead class="bg-black flex text-white w-full">
                    <tr class="flex w-full mb-1">
                        <th class="p-4 w-1/4">Sno</th>
                        <th class="p-4 w-1/4">Name</th>
                        <th class="p-4 w-1/4">Email</th>
                        <th class="p-4 w-1/4">Total Post</th>
                        <th class="p-4 w-1/4">Roles</th>
                        <th class="p-4 w-1/4">Created</th>
                        <th class="p-4 w-1/4">Action</th>

                    </tr>
                </thead>
                <!-- Remove the nasty inline CSS fixed height on production and replace it with a CSS class — this is just for demonstration purposes! -->
                <tbody class="bg-grey-light flex flex-col items-center justify-between overflow-y-scroll w-full h-full">
                    <?php $i = 1; ?>
                    @foreach ($users as $user)
                        <tr class="flex w-full mb-0">
                            <td class="p-4 w-1/4">{{ $i++ }}</td>
                            <td class="p-4 w-1/4">{{ $user->name }}</td>
                            <td class="p-4 w-1/4">{{ $user->email }}</td>
                            <td class="p-4 w-1/4">{{ $user->posts->count() }}</td>
                            <td class="p-4 w-1/4">
         {{ implode(', ',$user->roles()->get()->pluck('name')->toArray()) }} 
                            </td>
                            <td class="p-4 w-1/4">{{ $user->created_at->diffForHumans() }}</td>

                            <td class="p-4 w-1/4">
                                <form action="{{ route('admin.users.destroy', $user->id) }}" method="post">
                                    @csrf
                                    @method('delete')
                                    <input type="submit" class="hover:underline  text-blue-900" value="DELETE">
                                </form>
                                <a class="hover:underline text-blue-900 font-bold"
                                    href="{{ route('admin.users.edit', $user->id) }}">EDIT</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <h1 class="text-center mt-10">No Post</h1>
        @endif
    </div>
    <script>
        $("#success-alert").fadeTo(2000, 500).slideUp(500, function() {
            $("#success-alert").slideUp(500);
        });
        $(document).ready(function() {
            $("#success-alert").hide();
            $("#myWish").click(function showAlert() {
                $("#success-alert").fadeTo(2000, 500).slideUp(500, function() {
                    $("#success-alert").slideUp(500);
                });
            });
        });
    </script>
@endsection