routes/web.php
<?php

use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AdminPostController;

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Http\Controllers\PostController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\LikeController;
use App\Http\Controllers\PaymentController;

Route::get('/', [PostController::class, 'index'])->name('post.index');
Route::get('/post/{post}', [PostController::class, 'show'])->name('post.show');

Route::get('/post/search', [PostController::class, 'search'])->name('post.search');

Auth::routes(['verify' => true]);

Route::middleware('guest')->group(function () {
    Route::get('/register', [AuthController::class, 'indexRegister'])->name('indexRegister');
    Route::post('/register', [AuthController::class, 'register'])->name('register');
    Route::get('/login', [AuthController::class, 'index'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->name('customLogin');

});

Route::post('/logout', function () {
    Auth::logout();
    return redirect('/')->with('logoutMsg', 'Logout Successfully');
})->name('logout');

Route::get('/home', function () {
    return redirect('/');
});


Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/user/create', [PostController::class, 'showCreateForm'])->name('post.create')->middleware('subscription');
    Route::post('/user/create', [PostController::class, 'store'])->name('post.store')->middleware('subscription');
    Route::get('/user/posts/', [PostController::class, 'singleUserPosts'])->name('user.posts');
    Route::get('/user/posts/{id}', [PostController::class, 'edit'])->name('user.posts.edit');
    Route::put('/user/posts/{id}', [PostController::class, 'update'])->name('user.posts.update');
    Route::delete('/user/posts/{id}', [PostController::class, 'destroy'])->name('user.posts.delete');

    Route::get('posttable', [PostController::class, 'tableView'])->name('post.table');
    Route::get('posttable/sort-ascend', [PostController::class, 'sortByAscendTable'])->name('post.sort.ascend');
    Route::get('posttable/sort-older', [PostController::class, 'sortByOlderTable'])->name('post.sort.older');

    Route::get('/subscription/', [PaymentController::class, 'index'])->name('payment.index');
    Route::get('/subscription/silver', [PaymentController::class, 'silverSubscription'])->name('payment.silver');
    Route::get('/subscription/diamond', [PaymentController::class, 'diamondSubscription'])->name('payment.diamond');
    Route::get('/paypal-checkout/{price}', [PaymentController::class, 'paypalCheckout'])->name('paypal.checkout');

    Route::post('posts/{post}/like', [LikeController::class, 'store'])->name('posts.likes');
    Route::delete('posts/{post}/like', [LikeController::class, 'destroy'])->name('posts.likes');

    Route::post('comment/store/{post}',[CommentController::class,'store'])->name('comment.store');

});

Route::prefix('admin', 'verified')->name('admin.')->middleware('can:manage-users')->group(function () {
    Route::resource('/users', UserController::class)->except(['show', 'create', 'store']);
    Route::get('/posts/', [AdminPostController::class, 'index'])->name('posts.table');
    Route::delete('/posts/{id}', [AdminPostController::class, 'destroy'])->name('posts.delete');
    Route::get('/posts/{id}', [AdminPostController::class, 'edit'])->name('posts.edit');
    Route::put('/posts/{id}', [AdminPostController::class, 'update'])->name('posts.update');

    Route::get('posttable/sort-ascend', [AdminPostController::class, 'sortByAscendTable'])->name('post.sort.ascend');
    Route::get('posttable/sort-older', [AdminPostController::class, 'sortByOlderTable'])->name('post.sort.older');
    Route::get('posttable/sort-active', [AdminPostController::class, 'showActivePost'])->name('post.sort.active');
    Route::get('posttable/sort-notactive', [AdminPostController::class, 'showNotActivePost'])->name('post.sort.notactive');


    Route::post('/import', [UserController::class, 'import'])->name("user.import");
    Route::get('/export', [UserController::class, 'export'])->name("user.export");
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use PDO;

class Post extends Model
{
    use HasFactory;

    protected $fillable = ['title','description','image'];

    public  function user(){
        return $this->belongsTo(User::class);
    }

    public function likedBy(User $user) {
        return $this->likes->contains('user_id',$user->id);
    }

    public function likes() {
        return  $this->hasMany(Like::class);
    }

    public function comments(){
        return $this->morphMany(Comment::class,'commentable')->latest()->whereNull('parent_id');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Carbon;
use App\Models\Payment;

class PostController extends Controller
{
    public function  index()
    {
        $posts = Post::with('user','likes','comments')->where('status', 0)->orderBy('created_at', 'desc')->paginate(10);
        return  view('post.index', ['posts' => $posts]);
    }

    public function search(Request $request)
    {
        $search = $request->search;
        $posts = Post::with('user')->where('status', 0)->where('title', 'like', '%' . $search . '%')->paginate(5);
        return view('post.index', ['posts' => $posts]);
    }

    // ALL FUNCTION DOWN BELOW REQUIRES AUTHENTICATION && DEPEND ON SINGLE USER RECORDS

    public function showCreateForm()
    {
        return view('post.create');
    }

    public function store(Request  $request)
    {
        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'image' => 'required|mimes:jpg,png,jpeg|max:5048',
        ]);

        $imageName = time() . '-' . $request->title . '.' . $request->image->extension();
        $post = $request->user()->posts()->create([
            'title' => $request->title,
            'description' => $request->description,
            'image' => $imageName,
        ]);
        $request->image->move(public_path('images'), $imageName, 's3');
        $incrementPostCounter = Payment::where('user_id', $request->user()->id)->first();
        $incrementPostCounter->post_count -= 1;
        $incrementPostCounter->save();

        return redirect('/')->with('post-approval', 'Your post is submitted for admin Approval');
    }

    public function edit($id)
    {
        $user_id = Auth::id();
        $post = Post::find($id);
        if ($user_id == $post->user_id)
            return view('post.edit', ['post' => $post]);
        return back();
    }

    public function show(Post $post){
        $post->with('comments','replies');
        // dd("dd");
        return view('post.show',['post'=>$post]);
    }

    public function update(Request $request, $id)
    {
        $post = Post::find($id);
        $user_id = Auth::id();
        if ($user_id == $post->user_id) {
            if ($request->image != null) {
                $imageUrl = time() . '-' . $request->name . '.' . $request->image->extension();
                $request->image->move(public_path('images'), $imageUrl, 's3');
            } else
                $imageUrl = $post->image;
            $post->update(
                [
                    'title' => $request->title,
                    'description' => $request->description,
                    'image' =>  $imageUrl,
                ]
            );
        }
        return redirect()->route('post.table');
    }


    // SHOW POST OF CURRENT AUTH USER
    public function singleUserPosts(Request $request)
    {
        $posts = $request->user()->posts()->orderBy('created_at', 'desc')->paginate(5);
        return view('post.index', ['posts' => $posts]);
    }

    public function allPost()
    {
        $posts = Post::paginate(10);
        return view('admin.posts.post_table', ['posts' => $posts]);
    }

    // USER POST TABLE DATA
    public function  tableView(Request $request)
    {
        $posts = Post::where('user_id', $request->user()->id)->orderBy('created_at', 'desc')->paginate(5);
        // $posts = $request->user()->posts()->orderBy('created_at', 'desc')->paginate(5);
        return  view('post.post_table', ['posts' => $posts]);
    }

    // USER POST TABLE DATA ASCENDING ORDER
    public function sortByAscendTable(Request $request)
    {
        $posts = Post::where('user_id', $request->user()->id)->paginate(5);
        Session::flash('acsend', 'Showing in Acsending Order');
        return  view('post.post_table', ['posts' => $posts]);
    }

    // USER POST TABLE DATA OLDER POST FIRST
    public function sortByOlderTable(Request $request)
    {
        $posts = Post::where('user_id', $request->user()->id)->orderBy('created_at')->paginate(5);
        Session::flash('success', 'showing Older first');
        return view('post.post_table', ['posts' => $posts])->with('msg', 'showing Older first');
    }

    public function destroy(Request $request, $id)
    {
        $post = Post::where('user_id', $request->user()->id)->where('id',$id);
        $post->delete();
        return back()->with('msg', 'Post Deleted');
    }
}

resources/views/admin/posts/post_table.blade.php
@extends('layouts.app')

@section('content')




    @if (Session::has('success'))
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Succeed</strong> {{ Session::get('success') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
    @if (Session::has('approved'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>Succeed</strong> {{ Session::get('approved') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
    @if (Session::has('acsend'))
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Succeed</strong> {{ session('acsend') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
    <!-- Example single danger button -->
    <!-- Example split danger button -->
    <div class="container ">
        <h1 class="mb-8 mt-4 text-xl float-left">Post Table</h1>

        <div class="dropdown mb-2 mr-3 mt-3 text-right float-right">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Sort by
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                <form action="{{ route('admin.post.sort.notactive') }}" method="get"><button class="dropdown-item"
                        type="submit">Need Approval Post</button></form>
                <form action="{{ route('admin.post.sort.active') }}" method="get"><button class="dropdown-item"
                        type="submit">Approved Post</button></form>
                <form action="{{ route('admin.post.sort.ascend') }}" method="get"><button class="dropdown-item"
                        type="submit">Sort by A-Z</button></form>
                <form action="{{ route('admin.post.sort.older') }}" method="get"><button class="dropdown-item"
                        type="submit">Show Older first</button></form>



            </div>



        </div>
        @if ($posts->count())
            <table class="text-center w-full h-auto">
                <thead class="bg-black flex text-white w-full">
                    <tr class="flex w-full mb-1">
                        <th class="p-4 w-1/4">Sno</th>
                        <th class="p-4 w-1/4">Title</th>
                        <th class="p-4 w-1/4">Image</th>
                        <th class="p-4 w-1/4">Description</th>
                        <th class="p-4 w-1/4">Post By</th>
                        <th class="p-4 w-1/4">Approved</th>
                        <th class="p-4 w-1/4">Created</th>
                        <th class="p-4 w-1/4">Action</th>

                    </tr>
                </thead>
                <!-- Remove the nasty inline CSS fixed height on production and replace it with a CSS class — this is just for demonstration purposes! -->
                <tbody class="bg-grey-light flex flex-col items-center justify-between overflow-y-scroll w-full h-96">
                    <?php $i = 1; ?>
                    @foreach ($posts as $post)
                        <tr class="flex w-full mb-10">
                            <td class="p-4 w-1/4">{{ $i++ }}</td>
                            <td class="p-4 w-1/4">{{ $post->title }}</td>
                            <td class="p-4 w-1/4"><img src="{{ asset('images/' . $post->image) }}" height="30"
                                    width="80"></td>
                            <td class="p-4 w-1/4">{{ substr($post->description, 0, 100) }}</td>
                            <td class="p-4 w-1/4">{{ substr($post->user->name, 0, 100) }}</td>
                            <td class="p-4 w-1/4">
                                <form action="{{ route('admin.posts.update', $post->id) }}" method="POST">
                                    @method('put')
                                    @csrf
                                    @if ($post->status == 1)
                                        <input name="status" type="hidden" value="0">
                                        <button type="submit" class="btn btn-danger">No</button>
                                    @else
                                        <input name="status" type="hidden" value="1">
                                        <button type="submit" class="btn btn-primary">Yes</button>
                                    @endif
                                </form>
                            </td>
                            <td class="p-4 w-1/4">{{ $post->created_at->diffForHumans() }}</td>
                            <td class="p-4 w-1/4">
                                <form action="{{ route('admin.posts.delete', $post->id) }}" method="post">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="hover:underline btn btn-warning">DELETE</button>
                                </form>

                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <h1 class="text-center mt-10">No Post</h1>
        @endif
    </div>
    <script>
        $("#success-alert").fadeTo(2000, 500).slideUp(500, function() {
            $("#success-alert").slideUp(500);
        });
        $(document).ready(function() {
            $("#success-alert").hide();
            $("#myWish").click(function showAlert() {
                $("#success-alert").fadeTo(2000, 500).slideUp(500, function() {
                    $("#success-alert").slideUp(500);
                });
            });
        });
    </script>
@endsection