routes/web.php
<?php

use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AdminPostController;

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Http\Controllers\PostController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\LikeController;
use App\Http\Controllers\PaymentController;

Route::get('/', [PostController::class, 'index'])->name('post.index');
Route::get('/post/{post}', [PostController::class, 'show'])->name('post.show');

Route::get('/post/search', [PostController::class, 'search'])->name('post.search');

Auth::routes(['verify' => true]);

Route::middleware('guest')->group(function () {
    Route::get('/register', [AuthController::class, 'indexRegister'])->name('indexRegister');
    Route::post('/register', [AuthController::class, 'register'])->name('register');
    Route::get('/login', [AuthController::class, 'index'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->name('customLogin');

});

Route::post('/logout', function () {
    Auth::logout();
    return redirect('/')->with('logoutMsg', 'Logout Successfully');
})->name('logout');

Route::get('/home', function () {
    return redirect('/');
});


Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/user/create', [PostController::class, 'showCreateForm'])->name('post.create')->middleware('subscription');
    Route::post('/user/create', [PostController::class, 'store'])->name('post.store')->middleware('subscription');
    Route::get('/user/posts/', [PostController::class, 'singleUserPosts'])->name('user.posts');
    Route::get('/user/posts/{id}', [PostController::class, 'edit'])->name('user.posts.edit');
    Route::put('/user/posts/{id}', [PostController::class, 'update'])->name('user.posts.update');
    Route::delete('/user/posts/{id}', [PostController::class, 'destroy'])->name('user.posts.delete');

    Route::get('posttable', [PostController::class, 'tableView'])->name('post.table');
    Route::get('posttable/sort-ascend', [PostController::class, 'sortByAscendTable'])->name('post.sort.ascend');
    Route::get('posttable/sort-older', [PostController::class, 'sortByOlderTable'])->name('post.sort.older');

    Route::get('/subscription/', [PaymentController::class, 'index'])->name('payment.index');
    Route::get('/subscription/silver', [PaymentController::class, 'silverSubscription'])->name('payment.silver');
    Route::get('/subscription/diamond', [PaymentController::class, 'diamondSubscription'])->name('payment.diamond');
    Route::get('/paypal-checkout/{price}', [PaymentController::class, 'paypalCheckout'])->name('paypal.checkout');

    Route::post('posts/{post}/like', [LikeController::class, 'store'])->name('posts.likes');
    Route::delete('posts/{post}/like', [LikeController::class, 'destroy'])->name('posts.likes');

    Route::post('comment/store/{post}',[CommentController::class,'store'])->name('comment.store');

});

Route::prefix('admin', 'verified')->name('admin.')->middleware('can:manage-users')->group(function () {
    Route::resource('/users', UserController::class)->except(['show', 'create', 'store']);
    Route::get('/posts/', [AdminPostController::class, 'index'])->name('posts.table');
    Route::delete('/posts/{id}', [AdminPostController::class, 'destroy'])->name('posts.delete');
    Route::get('/posts/{id}', [AdminPostController::class, 'edit'])->name('posts.edit');
    Route::put('/posts/{id}', [AdminPostController::class, 'update'])->name('posts.update');

    Route::get('posttable/sort-ascend', [AdminPostController::class, 'sortByAscendTable'])->name('post.sort.ascend');
    Route::get('posttable/sort-older', [AdminPostController::class, 'sortByOlderTable'])->name('post.sort.older');
    Route::get('posttable/sort-active', [AdminPostController::class, 'showActivePost'])->name('post.sort.active');
    Route::get('posttable/sort-notactive', [AdminPostController::class, 'showNotActivePost'])->name('post.sort.notactive');


    Route::post('/import', [UserController::class, 'import'])->name("user.import");
    Route::get('/export', [UserController::class, 'export'])->name("user.export");
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    <script src="{{ asset('js/app.js') }}"></script>
    <title>Document</title>

</head>
<body>
    <nav>
        <div class="">
            <div class="flex justify-between h-16 px-10 shadow items-center">
                <div class="flex items-center space-x-8">
                    <h1 class="text-xl lg:text-2xl font-bold cursor-pointer">CRUD APP</h1>
                    <div class="hidden md:flex justify-around space-x-4">
                        <a href="/" class="hover:text-indigo-600 text-gray-700">Home</a>
                        @auth
                            <a href="{{ route('post.table') }}" class="hover:text-indigo-600 text-gray-700 ">My
                                Post</a><sup class="ml-1 mb-1 hover:text-indigo-600 text-gray-700 font-bold text-base">
                                {{ auth()->user()->posts()->count() ?? '0' }}</sup>
                            <a href="{{ route('post.create') }}" class="hover:text-indigo-600 text-gray-700">Create
                                Post</a>
                            @if(auth()->user()->hasRole('user'))
                            <a href="{{ route('payment.index') }}"
                            class="hover:text-indigo-600 text-gray-700">Subscriptions</a>
                            @endif
                        @endauth
                    </div>
                </div>

                <!-- component -->
                <!-- This is an example component -->
                <form method="get" action="{{ route('post.search') }}">
                    <div class="pt-2 relative mx-auto text-gray-600">
                        <input
                            class="border-2 border-gray-300 bg-white h-10 px-5 pr-16 rounded-lg text-sm focus:outline-none"
                            type="search" name="search" placeholder="Search">
                        <button type="submit" class="absolute right-0 top-0  mt-3 mr-4">
                            <svg class="text-gray-600 h-4 w-4 fill-current" xmlns:xlink="http://www.w3.org/1999/xlink"
                                x="0px" y="0px" viewBox="0 0 56.966 56.966"
                                style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve" width="512px"
                                height="512px">
                                <path
                                    d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z" />
                            </svg>
                        </button>
                    </div>
                </form>

                @guest
                    <div class="flex space-x-4 items-center">
                        <a href="{{ route('customLogin') }}" class="text-gray-800 text-sm">LOGIN</a>
                        <a href="{{ route('register') }}"
                            class="bg-indigo-600 px-4 py-2 rounded text-white hover:bg-indigo-500 text-sm">SIGNUP</a>
                    </div>
                @endguest
                @auth
                    @can('manage-users')
                        <div class="flex space-x-4 ">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Admin Actions
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('admin.users.index') }}">View Users</a>
                                <a class="dropdown-item" href="{{ route('admin.posts.table') }}">Posts</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </div>
                    @endcan

                    <div class="flex space-x-4 items-center">
                        <h1 class="text-xl text-blue-500 lg:text-1xl font-bold cursor-pointer">{{ auth()->user()->name }}   
                        </h1>
                        <form method="post" action="{{ route('logout') }}">
                            @csrf
                            <button type="submit" class="text-gray-800 text-sm">SignOut</button>
                        </form>
                    </div>



                @endauth
            </div>
        </div>
    </nav>
    @yield('content')
</body>

</html>